version: '3.8'

services:
  web:
    build: .
    image: myapp:latest
    command: bash -c "python3 manage.py makemigrations 
            && python3 manage.py migrate 
            && python manage.py collectstatic --no-input 
            && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
 
