---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker
    tag: "20.10.8"

inputs:
  - name: ice-cream-repo

run:
  path: sh
  args:
    - -exc
    - |
      echo "docker build repo2 updated"
      docker build -t repo-2-app .
